name: multi_select_bottom_sheet
description: A Flutter package to display a multi selection drop down widget.
version: 1.0.0+1
homepage: https://github.com/SteelTitan247/custom_searchable_dropdown
repository: https://github.com/SteelTitan247/custom_searchable_dropdown.git

environment:
  sdk: ">=2.17.0 <4.0.0"
  flutter: ">=1.12.0"

dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:

  uses-material-design: true
  plugin:
    platforms:
      android:
        package: custom_dropdown
        pluginClass: MultiSelectionDropDownPlugin
        ios:
          pluginClass: MultiSelectionDropDownPlugin